import Head from "next/head";
import { Center, ChakraProvider } from "@chakra-ui/react";
import clsx from "clsx";
import LoFiForm from "./components/LoFiForm";

export default function Home() {
  return (
    <ChakraProvider>
      <Head>
        <title>Lo-Fi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <main className="h-full min-h-screen max-w-7xl bg-slate-500 pb-12">
          <section className={clsx("pb-8", "p-1", "flex", "justify-center")}>
            <img
              className={clsx("shadow-xl")}
              src="https://i.imgur.com/boTI4vS.gif"
            />
          </section>
          <section className={clsx("pb-8", "p-1", "flex")}>
            <LoFiForm />
          </section>
        </main>
      </Center>
    </ChakraProvider>
  );
}
